version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres15
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go-chat
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      - postgres
    volumes:
      - ./db/migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database",
        "postgres://root:password@postgres:5432/go-chat?sslmode=disable",
        "up"
      ]
    restart: "no"

volumes:
  pgdata:
